qt6: Fix build with QT_USE_QSTRINGBUILDER
httprequest.cpp:374:44: error: no matching function for call
    to ‘QByteArray::startsWith(QStringBuilder<char [3], QByteArray>)’
374 |                         if (line.startsWith("--" + boundary)) {

httprequest.cpp:406:50: error: no matching function for call
    to ‘QByteArray::contains(QStringBuilder<QByteArray, char [3]>)’
406 |                                 if (line.contains(boundary + "--")) {

Also we don't change the boundary during the loop so we don't need to
create helper strings every iteration.